### ISSUE TITLE
CKE5 v.12.0 support?

### ISSUE THREAD

**Issue by NishealJ** [centaur54dev/ckeditor5-math-preview#2]
Seems like not working with CKE 12.0.0, nothing happens when the plugin is clicked.

**Comment by centaur54dev** [comment]
I am using it currently with ck5 v12 without problem. Did it work for you before and stopped working after upgrading?

Btw the toolbar button works as a toggle that enables/disables the plugin functionality. Nothing obvious happens when you click it. To check that it works, type this to the editor:
`\(x+x^2=0\) `
then click-enable the plugin from the toolbar (if disabled), and then click with mouse somewhere between the parentheses. A popup should display the rendered equation.

Edit:
Updated dependencies for the latest ckeditor5 v.12.1.0.

**Comment by centaur54dev** [comment]
Do you have any new updates regarding this issue? Have you managed to use the plugin?

**Comment by centaur54dev** [comment]
Closed because no feedback was provided on the issue for a long time. 
If the issue is still relevant please create a new one.
