### ISSUE TITLE
setData() seems not to work properly when setting a latex formula

### ISSUE THREAD

**Issue by ETHwsch** [centaur54dev/ckeditor5-math-preview#6]
Which is the correct way of calling editor.setData( ) with a latex formula as an argument?

I tried  **editor.setData( "\\\\[a+b\\\\]" );** and I am getting **a+ba+b** 
If a call  **editor.setData( "\\[a+b\\]" );**  and I am getting **[a+b]** 

The expected result in the editor should be **\\[a+b\\]**.

Any idea?

**Comment by nexterday** [comment]
The block of code below needs to be adjusted to not add the text twice when setData is called when containing a latex formula (even when its prefilled in a textarea).

		this.editor.editing.model.change( writer => {
			if (!modelRng.isCollapsed){
				writer.remove(modelRng);
			}
			const txt = writer.createText(newmath)
			writer.insert(txt, modelPos0);
			writer.setSelection(modelPos0.getShiftedBy(2));
		} );

**Comment by centaur54dev** [comment]
Sorry for the delayed response, i somehow missed the notification.
This issue occurs even without loading the plugin. Tested with a fresh install of ckeditor5 v16. I will open an issue in official ckeditor5. 

It is remarkable that the issue occurs only during editor initialization. The following code works normally:
 ```
ck5editor = ClassicEditor
	        .create(  editorDiv )
	        .then( (editor) => {
                    //do nothing in here
                 })

....
//after editor is rendered
ck5editor.setData("\\[a+b\\]")
```

**Comment by ETHwsch** [comment]
(copied from here https://github.com/ckeditor/ckeditor5/issues/5906)

I can confirm that a plain Ckeditor 5 version works correctly: https://jsfiddle.net/Lvywge37/4/

The error seems to be related to the ckeditor5-math-preview plugin: https://github.com/centaur54dev/ckeditor5-math-preview#readme
An example which envisions the wrong behavior can be seen here: https://jsfiddle.net/ub472vq6/

**Comment by nexterday** [comment]
I think you need to come back to the original code block above and play around with the .change and use inside it (or change it) to enqueueChange ao you can make the order right.

.change(...
. enqueueChange(..

Have no access to test it on your plugin though.

<code>

model.change( writer => {
    console.log( 1 );
    model.enqueueChange( writer => {
        console.log( 2 );
    } );
    console.log( 3 );
} ); 


// Will log: 1, 3, 2.
</code>

**Comment by centaur54dev** [comment]
After some more testing it seems that the problem is caused by the MathJax library, that typesets the early document. So you need to prevent MathJax from automatically rendering the page at startup. This can be done with the `skipStartupTypeset` directive. A quick example on custom MathJax loading:
```
<script async src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-AMS_HTML'></script>
<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
       skipStartupTypeset:true
    });
  </script>
```

Alternatively, you may delay the setData command until MathJax has finished rendering. Just push the setData command in the MathJax queue:
```
MathJax.Hub.Queue(function () {
        editor.setData("<p>\\[x=0\\]</p>");
 });
```
Make sure though to run the above code after MathJax is initialised. A working jsffidle is [here](https://jsfiddle.net/centaur54dev/f97qv2at/). 

@nexterday , the code block you refer to, executes only when the user clicks an option on the popup window. I can't figure out how this interferes with realtime rendering of the ckeditor model.

**Comment by ETHwsch** [comment]
Thanks! This works for me. Issue can be closed.
